# Generated by Django 5.1.1 on 2024-10-11 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectWebGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ProjectWebGame.game'),
            preserve_default=False,
        ),
    ]
