# Generated by Django 5.1.2 on 2024-10-20 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ProjectWebGame", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Draft",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
