# Generated by Django 5.1.1 on 2024-10-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectWebGame', '0002_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
