# Generated by Django 5.1.1 on 2024-10-11 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectWebGame', '0002_comment_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
