# Generated by Django 5.1.1 on 2024-10-16 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectWebGame', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
