# Generated by Django 5.1.1 on 2024-10-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectWebGame', '0002_userprofileinfo_is_vip_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_vip',
            field=models.BooleanField(default=False),
        ),
    ]
